import { NewsCardProps } from "@/interfaces";

export default [
  {
    id: 1,
    title: "Co kryje dolina Tyśmienicy",
    coordinates: [22.731593672017237, 51.656679094862625],
    date: "28/04/2008",
    subHeader:
      "Naukowcy i regionaliści z południowego Podlasia chcą przeprowadzenia kompleksowych badań archeologicznych doliny rzeki Tyśmienicy.",
    images: ["/assets/prasa/izis-co-kryje-dolina-tyśmienicy.webp"],
    source: "Dziennik Wschodni",
    type: "archaeological-supervision-earthworks",
    url: "/prasa-o-nas/co-kryje-dolina-tysmienicy",
    content: [
      "W Bełczącu odkryliśmy ślady centrum osadniczego. Znaleźliśmy tam narzędzia krzemienne i przedmioty z okresu brązu. Z kolei w Niewęgłoszu okazało się , że 8 tysięcy lat przed Chrystusem istniała tam osada. Chcieliśmy prowadzić tam wykopaliska wspólnie z Radzyńską Izbą Historyczną, ale nasz projekt został negatywnie oceniony przez komisję z ministerstwa. Nie dostaniemy więc dotacji i sami musimy częściowo sfinansować badania - mówi Mieczysław Bienia, bialski archeolog.",
      "Bienia przyznaje, że szczególnie interesuje go teren w dolinie Tyśmienicy. Spodziewa się tu znaleźć kolejne groby z okresu przedrzymskiego. Razem z radzyńskimi regionalistami zabiega o kompleksowe badania archeologiczne na terenie gminy Czemierniki. O to samo walczy Marian Mazurek, historyk który opracowuje monografię gminy. Mazurek przekazał do Muzeum Południowego Podlasia krzemienny toporek, grot oszczepu i miecz Wikingów, który odkupił od jednego z rolników.",
      "Przez wiele lat trzymałem ten miecz w szkole. Pokazywałem go uczniom, mogli go dotknąć. Na kawałek zardzewiałego metalu patrzę inaczej niż inni - mówi Mazurek. W dolinie Tyśmienicy osadnictwo kwitło przez wiele epok. Musimy zrobić wszystko, aby zostały tu przeprowadzone kompleksowe badania archeologiczne - dodaje historyk. I przyznaje, iż bardzo liczy na pomoc posła Tadeusza Sławeckiego. Poseł jest prezesem Czemiernickiego Towarzystwa Regionalnego.",
      "W przyszłym roku będziemy obchodzić jubileusz 500-lecia Czemiernik. Wydamy obszerną monografię. Trwają też prace nad planem rewitalizacji osady Czemierniki - mówi Sławecki.",
    ],
  },
  {
    id: 2,
    title: "Radarem będą szukać kości",
    coordinates: [19.140204510107285, 50.4256616918065],
    date: "24/06/2008",
    subHeader:
      "Nadal nie wiadomo, gdzie mogą spoczywać szczątki nieznanych Polaków, rzekomo zamordowanych pod koniec lat 40. w Toporowie.",
    source: "Słowo Podlasia",
    type: "preventive-archaeological-research",
    url: "/prasa-o-nas/radarem-beda-szukac-kosci",
    images: ["/assets/prasa/izis-radarem-beda-szukac-kosci.webp"],
    content: [
      "Wykrywaczem metalu znaleziono w piwnicy łuskę po naboju wystrzelonym z pepeszy lub tetetki. Dziury w ścianie mogą być otworami po kulach. Tam, gdzie miał być grób, znaleziono w ziemi kawałek przestrzelonej blachy, na której prawdopodobnie żołnierze ćwiczyli strzały. Szczątków ciał jednak nie wykryto.",
      "Zapowiedź ekshumacji zaintereso wała kombatantów, wywołała dyskusje wśród mieszkańców, którzy pamiętają pierwsze powojenne lata. Do Toporowa przyjechał specjalnie w tym dniu mjr rez. Tadeusz Sobieszczak, partyzant AK z oddziału Zenona. Zjawili się historycy. Wykopy prowadzone były w miejscu wskazanym przez inicjatora akcji Tadeusza Lesiuka i potwierdzonym przez jasnowidza. Przy wejściu do piwnicy zrujnowanego pałacu archeolog Mieczysław Bienia nie odkrył jednak zbiorowego grobu. Zbrodnia miała do konać się w przedsionku do piwnicy rękami funkcjonariuszy sowieckiego NKWD lub polskiego KBW i UB. Przez godzinę wynajęci mężczyźni kopali szpadlami w oznaczonym kwadracie. Rosło tam drzewo, które jesienią wyciął Tadeusz Lesiuk, szukając szczątków na własną rękę.",
      "Po zdjęciu płytkiej warstwy gleby kopiący dotarli do gliny. - Z pewnością w tym miejscu był dół, ale nie na zbiorowy pochówek. To mogło być oczko wodne. Mamy tu także pozostałości fundamentów jakiejś budowli wcześniejszej W tym miejscu na pewno nie ma szczątków ludzkich niż pałac. Niepowodzenie, to jednocześnie sukces. Wiemy już, że w tym miejscu nie ma ciał. Będziemy szukać dalej. Pozyskamy lepszy sprzęt - mówi Mieczysław Bienia. Sondowanie ziemi w kilku innych miejscach na terenie parku dało podobne rezultaty.",
      "Zdaniem Mirosława Barczyńskiego z Muzeum Południowego Podlasia w Białej Podlaskiej, zabici w pałacowej piwnicy nie mogli być zakopani tak blisko budynku, który stał wówczas na odkrytym, niezadrzewionym terenie. - Bardziej prawdopodobne jest, że spoczywają na fot. B. Malczuk terenie starego parku. Tutaj jest zbyt mało miejsca na tak duży grób. Każdą informację mamy obowiązek sprawdzić, trzeba kontynuować działania zauważył Barczyński. Pierwsze niepowodzenie nie zraziło szukających. Zamierzają wynająć georadar, który wskaże potencjalne miejsca pochówku. Ślady krwi na ścianach piwnicy wykryte będą podczerwienią. Najlepszym rozwiązaniem będzie użycie georadaru, bo całego parku nie przekopiemy szpadlami. Możemy też poczekać do jesieni i przy użyciu koparki odkryć większą powierzchnię gruntu zauważa Mieczysław Bienia.",
      "Jak po grudzie idzie reaktywacja muzeum w Łosicach. Samorząd miasta i gminy nie chce dotować działalności jedynej tego typu placówki. Na eksponatach osiada kurz w magazynie, a mogłyby służyć poszerzaniu wiedzy o historii Ziemi Łosickiej. Zbiory zlikwidowanej przed laty filii pracownika, który będzie doglądał eksmuzeum w Białej Podlaskiej przechowuje pozycji i udostępniał ją zwiedzającym. liceum w Łosicach. Nie mogą wspomagać edukacji młodzieży z kilku szkół eksponaty gromadzone latami przez Józefa Rumika, jednego z założycieli Towarzystwa Przyjaciół Ziemi Łosickiej. Kolekcjonował pamiątki, dokumenty, pieczęcie, numizmaty i wiejskie sprzęty gospodarskie. Na osobną ekspozycję zasługują żyjący niegdyś w Łosicach Żydzi. Przyjeżdżający na odrestaurowany cmentarz potomkowie chętnie zwiedziliby wystawę.",
      "Działacze towarzystwa postanowili stworzyć na nowo muzeum związane z historią i tradycją najbliższego terenu. Zabiegali o pomoc u władz powiatu oraz gminy, ale nie uzyskali wsparcia. To czysto społeczna i bardzo potrzebna inicjatywa. Dobiega końca remont użyczonej przez burmistrza siedziby towarzystwa w budynku dawnego szpitala i seminarium duchownego przy ulicy Berka Joselewicza. Dzięki sponsorom udało nam się sporo zrobić. W uporządkowaniu miejsca pomogła nam młodzież szkolna, ale bez dodatkowego wsparcia muzeum nie będzie mogło funkcjonować, zaznacza Tomasz Dobrowolski,historyk, prezes TPZŁ. Podkreśla, że składki członkowskie nie wystarczą na utrzymanie 120 mkw. wynajmowanej powierzchni. Trzeba ponadto zatrudnić na co najmniej pół etatu TAK DBAJĄ O KULTURĘ Niestety ani burmistrz, ani radni nie docenili zaangażowania społeczników. Potraktowali ich starania muzeum jak nikomu niepotrzebne widzimisię.",
      "Przewidziałem, że zechcą pieniędzy, kiedy w ubiegłym roku przychodzili do mnie w sprawie siedziby. Zarzekali się, że tak nie będzie, że znajdą sponsorów, i proszę. Mówiłem od razu, że ze sponsoringu nie utrzyma się takiej placówki. Rocznie potrzeba im na to 100 tys. złotych mówił burmistrz Janusz Kobyliński radnym, którzy na sesji rozważali, czy dać kasę TPZŁ. Radni, dyskutując nad wnioskiem, nie tylko go nie poparli, ale jeszcze ośmieszyli TPZŁ. Proponujemy przekazać tysiąc złotych, bo w końcu o kulturę musimy dbać zauważyła radna Grażyna Chomiuk. Tyle to ja mogę z własnej kieszeni wyjąć, bo dostałem podwyżkę - skwitował burmistrz. Inni radni wypowiadali się w podobnym tonie.",
      "Miastu należy się choćby mała izba pamięci. Szkoda, że nawet nas nie poinformowano, że na sesji sprawa będzie omawiana. Chętnie zabralibyśmy głoskomentuje stanowisko rady Tomasz Dobrowolski.",
    ],
  },
  {
    id: 3,
    coordinates: [21.622079270681066, 51.901629434382585],
    date: "01/01/2008",
    source: "Życie na gorąco",
    title: "Mamut na drodze!",
    subHeader:
      "W podwarszawskim Garwolinie przypadkiem natrafiono na szczątki prehistorycznego zwierzęcia",
    type: "salvage-excavation-research",
    url: "/prasa-o-nas/mamut-na-drodze",
    images: ["/assets/prasa/izis-mamut-na-drodze.webp"],
    content: [
      "Wyobrazić sobie chyba nie sposób niczego bardziej przewidywalnego niż budowa drogi. Zadanie proste do wykonania, zwłaszcza dla fachowców, doktórych trudno nie zaliczyć specjalistów z Generalnej Dyrekcji Dróg Krajowych i Autostrad. Budują szybko, sprawnie, profesjonalnie. A ręce mają pełne roboty, bo, jak wiadomo, dróg w Polsce mało, samochodów dużo - potrzeby więc ogromne, a i determinacja ministerstwa transportu wielka.",
      "Jakież było więc zaskoczenie drogowców, kiedy w trakcie prac przy budowie obwodnicy Garwolina koło Warszawy nagle utknęli! Koparka niwelująca teren natrafiła na nie byle jaką przeszkodę. Najpierw były to potężne kły, a potem równie monstrualna czaszka. Wezwani na miejsce tak nietypowego znaleziska archeolodzy orzekli, że szczątkiowe mogły należeć jedynie do... mamuta!!!",
      "Kości jest kilka. Między nimi żuchwa z zębami, kilka kłów i miednicawyjaśnia badający wykopane fragmenty szkieletu archeolog Mieczysław Bienia. Twierdzi, że wszystkie zachowane są w znakomitym stanie. Co to wielkie prehistoryczne zwierzę robiło w okolicach Garwolina? To wykopalisko może rzucić nowe światło na to, co działo się na tych terenach przed 150 tysiącami lat. Wszystko zależy od tego, co uda się ustalić w trakcie dalszych badań archeologom. Już teraz zacierają oni ręce na myśl o planowanych ambitnych inwestycjach drogowych w naszym kraju. Liczą na to, że na trasie przebiegu kolejnych obwodnic, dróg ekspresowych i autostrad znalezionych zostanie wiele cennych szczątków prehistorycz Obwodnica Garwolina może zostać nazwana „mamucim szlakiem”.",
      "Nadzieje archeologów rozmijają się jednak zasadniczo z nadziejami drogowców. Ci ostatni woleliby nie napotykać już żadnych niespodzianek. W głowie im tylko kilometry nowiutkich, pokrytych czarniutkim asfaltem komunikacyjnych arterii. Bez żadnych przestojów.",
    ],
  },
  {
    id: 4,
    title: "Archeolog z wykształcenia i zamiłowania",
    coordinates: [23.1215161, 52.0329624],
    date: "05/09/2008",
    images: ["/assets/prasa/izis-archeolog-z-wyksztalcenia-i-zamilowania.webp"],
    source: "Tygodnik Podlaski",
    subHeader: "Marzyciel i pasjonat",
    url: "/prasa-o-nas/archeolog-z-wyksztalcenia-i-zamilowania",
    content: [
      "Mieczysław Bienia wychował się w Syrynii na Śląsku. Pokochał Podlasie, gdyż przyciągnęły go tajemnice, skrywane przez tutejsze ziemie. Założył więc rodzinę, wzniósł dom i zasadził drzewa. Podlasie stało się jego miejscem na Ziemi. Jest przekonany, iż w życiu dokonał słusznych wyborów, które pozwoliły mu na realizacje marzeń i pasji.",
      "AGNIESZKA LUBASZEWSKA komentuje następująco: Jako mały ośmioletni chłopiec podpatrywał czynnie prace archeologów, którzy prowadzili wykopaliska na rodzinnej działce. Udało się mu nawet wydobyć kilka skorup glinianych naczyń. W wieku szkolnym pasjonowały go dwie dziedziny - lotnictwo i historia. Ale wówczas musiałby iść do wojska i składać przysięgę na wierność Układowi Warszawskiemu i Związkowi Radzieckiemu. A na to nie pozwalały mu przekonania. Zrezygnował więcz lotnictwa i skupił się na historii. Wybrał archeologię na UMCS w Lublinie. To niema matka historii. Trzeba jej tajemnice odnaleźć, zinterpretować i ukazać światu - wyjaśnia Bienia. Po ukończeniu uczelni, do Białej przywiodła go chęć udowodnienia własnej tezy kolegom ze studiów. Usiłował ich bowiem przekonać, że przez teren południowego Podlasia przebiegał szlak wędrówki Gotów. Wskazywały na to stanowiska odkryte w okolicach Brześcia. Ponadto obszar byłego województwa bialskopodlaskiego stanowił białą plamę na mapie archeologicznej kraju. Dziewiczy teren, czyli świetne pole do realizacji swoich pomysłów, ziszczenia marzeń. To stanowiło prawdziwe wyzwanie dla młodego i zapalonego naukowca.",
      "ZAKOCHANY W KRESACH, Swej teorii nie potwierdził do dziś. Znalazł za to osadnictwo Bastarnów oraz udowodnił, że plemiona słowiańskie zamieszkiwały te tereny - nie jak przypuszczano od VIII ale od VI wieku. Fakt ten potwierdziły badania około 800 stanowisk wykopaliskowych. Do największych osiągnięć zalicza znalezisko w Horodyszczu. Tam odkrył osadę słowiańską. Relikty budynków zlokalizowanych na osi koła pochodzące z VIII wieku. Dzięki temu po raz pierwszy udało się zbadać osadę słowiańską na naszych terenach - mówi z entuzjazmem. Podlasie zauroczyło Mieczysława. Kresy okazały się nie tylko ciekawe pod względem archeologicznym. Tutaj na przestrzeni wieków styka]ły się granice państw, religie, kultury. Nigdzie nie spotyka się tak oryginalnej architektury drewnianej. Rosną tu obok siebie cerkwie unickie i prawosławne, kościoły, dworki oraz wiejskie chaty i wiatraki. - Najgorsze jest to, że mieszkańcy którzy tu się urodzili i żyją twierdzą zwykle, że tu nic ciekawego nie ma. Nie potrafili docenić otaczającego ich piękna zauważa.",
      "Dlatego też postanowił specjalizować się w archeologii Polski. Zgłębia niemą historię Podlasia, Mazowsza i Lubelszczyzny. Potwierdzeniem wzajemnych kontaktów między wschodnimi sąsiadami a naszymi terenami było odkrycie komory celnej z XII wieku. Ta wczesnośredniowieczna osada, w której funkcjonowało przejście graniczne usytuowana była w Bużyskach, niedaleko Korczewa.",
      "Podlasie zauroczyło Mieczysława. Kresy okazały się nie tylko ciekawe pod względem archeologicznym. Tutaj na przestrzeni wieków stykały się granice państw, religie, kultury. Nigdzie nie spotyka się tak oryginalnej architektury drewnianej. Rosną tu obok siebie cerkwie unickie i prawosławne, kościoły, dworki oraz wiejskie chaty i wiatraki.",
      "WYCZUCIE I SZCZĘŚCIE, Mieczysław od ponad dwudziestu lat odkrywa historię naszego regionu. Poprzez to o naszych korzeniach i kolejach losu wiemy coraz więcej. Wydobyte przez niego okazy archeologiczne pięknie prezentują się w muzeum. Jednak ich odnalezienie to kwestia ogromnej wiedzy, ciężkiej fizycznej pracy i szczęścia. Te wszystkie czynniki zadecydowały o znalezieniu osiedla Bastarnów w Dobryniu Małym. Ekipa tkwiła bowiem w przekonaniu, iż nie znajdzie tu nic ciekawego i przygotowywała się do odjazdu. W ostatniej chwili Mieczysław zdecydował sprawdzić jeszcze jedno stanowisko. Właśnie tam odkrył dowody potwierdzające, że trzy wieki przed Chrystusem osiadł tu lud germański, podążający w kierunku Morza Czarnego. Znaleziono tam pozostałości warsztatów tkackich, fragmenty naczyń, łyżkę glinianą oraz narzędzie do pielęgnacji twarzy dla mężczyzn.",
      "RODZINNA FIRMA, Bienia pracuje w Muzeum Południowego Podlasia. Prace archeologiczne wykonuje dla firmy „Izis”. Założyła ją z potrzeby chwili jego żona Małgorzata, również pasjonatka historii i archeologii. Prowadzenie działalności gospodarczej wiązało się bowiem z wykonaniem niektórych prac archeologicznych na zlecenie. Takimi sprawami nie miał czasu ani ochoty zajmować się Mieczysław, dlatego też wyręczyła go małżonka. Małgorzata czuwa nad sprawami organizacyjnymi, a nad wykopaliskami i opracowaniem naukowym pracuje jej mąż. Najnowsze techniki badawcze, jakimi obecnie posługują się archeolodzy pozwalają na precyzyjne określenie daty pochodzenia znaleziska z dokładnością do dwudziestu pięciu lat zapewnia. By być bliżej natury rodzina postanowiła zamieszkać na wsi. Zbudowała dom z drewnianego zabytkowego obiektu, który został przewieziony z Czemiernik.",
      "Mieszkanie wyposażyła Małgorzata. Żona posiada świetny zmysł architektury wnętrz. Znalazła niepowtarzalny sprzęt i ozdoby. Mam wrażenie, że mieszkamy w muzeum - chwali ją Mieczysław. Bieniowie posiadają dwiecórki - Klaudię i Julkę. Młodsza Julka od najmłodszych lat fascynuje się krzemieniami. Tatuś upatruje w córeczce swoją następczynię. Słowianie, ludność posługująca się językami słowiańskimi. Najliczniejsza indoeuropejska grupa ludnościowa w Europie, zamieszkująca wschodnią, środkową oraz południową część tego kontynentu. Do Słowian zalicza się: Białorusinów, Bośniaków, Bułgarów, Chorwatów, Czarnogórców, Czechów, Kaszubów, Ślązaków, Łemków, Macedończyków, Polaków, Rosjan, Serbołużyczan, Serbów, Słowaków, Słoweńców i Ukraińców oraz ponad 140 pomniejszych grup. Nazwa Słowianie, według jednej z licznych hipotez wzięła się od - słowa.",
    ],
  },
  {
    id: 5,
    title:
      "Leśna Podlaska pozwala odkrywać kolejne ciekawostki z zamierzchłych wieków",
    subHeader:
      "Badacze odkryli ciekawe miejsce podczas prac przed inwestycją gminną",
    url: "/prasa-o-nas/lesna-podlaska-pozwala-odkrywac-kolejne-ciekawostki-z-zamierzchłych-wiekow",
    coordinates: [23.034246760569424, 52.13544185017329],
    date: "02/12/2024",
    type: "archaeological-supervision-earthworks",
    source: "Radiobiper",
    images: [
      "/assets/prasa/izis-lesna-podlaska-pozwala-odkrywac-kolejne-ciekawostki-z-zamierzchłych-wiekow.webp",
      "/assets/prasa/izis-lesna-podlaska-pozwala-odkrywac-kolejne-ciekawostki-z-zamierzchłych-wiekow-2.webp",
      "/assets/prasa/izis-lesna-podlaska-pozwala-odkrywac-kolejne-ciekawostki-z-zamierzchłych-wiekow-3.webp",
      "/assets/prasa/izis-lesna-podlaska-pozwala-odkrywac-kolejne-ciekawostki-z-zamierzchłych-wiekow-4.webp",
      "/assets/prasa/izis-lesna-podlaska-pozwala-odkrywac-kolejne-ciekawostki-z-zamierzchłych-wiekow-5.webp",
      "/assets/prasa/izis-lesna-podlaska-pozwala-odkrywac-kolejne-ciekawostki-z-zamierzchłych-wiekow-6.webp",
      "/assets/prasa/izis-lesna-podlaska-pozwala-odkrywac-kolejne-ciekawostki-z-zamierzchłych-wiekow-7.webp",
    ],
    content: [
      "Prace poprzedzające jedną z inwestycji prowadzonych przez samorząd gminny odsłoniły ciekawe z punktu widzenia badaczy przeszłości miejsce. Kolejne ślady życia dawnych ludów zbadał w Leśnej Podlaskiej archeolog z Białej Podlaskiej Mieczysław Bienia, który podzielił się z nami własnymi uwagami na temat odkrywania zagadek przeszłości i ich wartości dla obecnych i przyszłych pokoleń. Plany związane z pamiątkami historii przybliżył natomiast wójt Paweł Kazimierski.",
      "Stanowisko prac archeologicznych zostało zlokalizowano tuż przed samą Leśną Podlaską, naprzeciwko cmentarza parafialnego, gdzie obecnie gmina realizuje jedną z inwestycji jaką jest wodociąg. Tradycyjnie prace budowlane poprzedzają badania prowadzone przez archeologów, ponieważ jest to gmina, na terenie której już wielokrotnie natrafiono na liczne ślady życia dawnych ludów.",
      "‟Mamy tu osadę z II wieku związaną z przemarszem germańskich Gotów, ale nie tylko, bo nieco dalej, bliżej rzeczki, mamy też osadę wczesnośredniowieczną, łużycką, nawet ze starszego okresu. Trzy lata temu, kiedy kopaliśmy na terenie przeznaczonym na parking, wyszły nam 22 obiekty: paleniska i jamy związane z kulturą wielbarską, z Gotami – wyjaśnił podczas rozmowy z redaktorem Radia Biper Mariuszem Maksymiukiem archeolog Mieczysław Bienia.”",
      "Na miejscu widoczny jest wykop o szerokości dwóch metrów i długości ponad 200 metrów. Zlokalizowano tu 12 obiektów podobnych do tych, które ujawniono trzy lata wcześniej, czyli jamy i paleniska z nielicznym materiałem ruchowym. ‟To bardzo ciekawe obiekty, bardzo płytko pod powierzchnią. Duża część z nich została zniszczona w trakcie orki. Ratujemy co się da dla poznania pradziejów, historii Leśnej Podlaskiej. To stanowisko niezwykle ciekawe, ponieważ tych śladów związanych z przemarszem Gotów mamy tutaj na tym terenie stosunkowo mało. Podobne stanowisko mamy w Witorożu, gdzie jest rozpoznanych kilka arów, czyli osada” – zauważył specjalista, według którego odkrywany obecnie teren mógł się cieszyć dużym osadnictwem z racji przepływającej przez niego rzeki oraz ówczesnego ciepłego, kontynentalnego klimatu. 30-40-letnia natomiast eksploatacja rolnicza terenu powodowała dalszy przemarsz i poszukiwanie nowego miejsca do życia i zakładania osady.” Na podstawie podobnych prac archeologicznych, m.in. ostatnio prowadzonych w pobliżu Huszlewa, w miejscowości Dziadkowskie, można stwierdzić, że dawni osadnicy mieszkali w budynkach drewnianych o konstrukcji słupowej. Liczne ślady ognisk świadczą o wykorzystaniu ich do przetwarzania żywności, jak i do produkcji „przemysłowej”, czyli do produkcji żelaza dominującego w wyrobie narzędzi. Ozdoby wykonywane były z brązu i ze srebra. Wśród ciekawych znalezisk m.in. fragment zapinki z brązu, tzw. fibuli, wykopanej podczas prac pod parkingiem.",
      "Ciekawe przedmioty z różnych stanowisk archeologicznych, m.in. z Witoroża, Dobrynia Małego, Zahajek czy Leśnej Podlaskiej, można oglądać w Muzeum Południowego Podlasia w Białej Podlaskiej. Na uwagę zasługują ozdobne elementy biżuterii, monety i narzędzia.",
      "‟Leśna Podlaska słynna była już jako teren pod lasem, nad Klukówką, niedaleko Bugu, czyli dużej arterii, którą kiedyś spławiano drzewa, również jako część szlaku bursztynowego. Dla nas w tej chwili ten teren znany jest od kultury neolitycznej. Odnajdujemy na tych terenach pierwsze artefakty, krzemienie, skrobaczki i inne różne kamienne przedmioty, więc jesteśmy w przedziale 8.000 lat p.n.e. Dziesięć tysięcy lat życia na tym terenie pozostawia artefakty różnych kultur” – zauważył wójt gminy Leśna Podlaska Paweł Kazimierski. Każda inwestycja wykonywana przez samorząd poprzedzana jest badaniami archeologicznymi. Wśród nich m.in. cztery stanowiska w Bordziłówce Starej odkryte podczas prac drogowych na długości 300 metrów, gdzie ujawniono ślady z XV-XVI w. Jest tam troszkę artefaktów, pan archeolog już je zinwentaryzował – wyjawił wójt, który zauważył że więcej na temat temat dowiemy się już wkrótce, ponieważ samorząd ma w planach przeprowadzenie szerzej zakrojonych badań archeologicznych na swoim terenie, niezwiązanych stricte z pracami inwestycyjnymi, właśnie po to, by jak najwięcej dowiedzieć się o dawnym życiu w tym regionie. – Chcemy sprawdzić i odkryć miejsca najciekawsze, w których uważamy, że znajdziemy dużo potwierdzeń kultury gockiej.",
      "Choć oficjalne plany nie są jeszcze bliżej sprecyzowane, możemy w przyszłości spodziewać się, czemu nie zaprzecza włodarz, efektownego miejsca w Leśnej Podlaskiej, w którym zostaną wyeksponowane ważne dla gminy i jej mieszkańców ślady dawnego osadnictwa oraz pamiątki historyczne.",
    ],
  },
  {
    id: 6,
    title: "Czy będzie sensacja archeologiczna?",
    subHeader:
      "Pod tymi warstwami kamieni kryją się prawdopodobnie pochówki kobiet z plemienia Gotów.",
    coordinates: [21.913024668535318, 53.08936662696098],
    date: "04/10/2002",
    source: "Gazeta Współczesna",
    type: "salvage-excavation-research",
    url: "/prasa-o-nas/czy-będzie-sensacja-archeologiczna",
    images: ["/assets/prasa/izis-czy-będzie-sensacja-archeologiczna.webp"],
    content: [
      "Uśnik, gmina Śniadowo. Ekipa archeologów wznowiła, rozpoczęte w ubiegłym roku, badania cmentarzyska kurhanowego z III w.n.e. Nie jest wykluczone, że w archeologii pojawi się nowy termin: ceramika z Uśnika.",
      "Cmentarzysko, na które składa się 10 kamiennych kurhanów (było ich prawdopodobnie około 14, ale część została zniszczona w wyniku upraw rolnych) znajduje się obecnie na prywatnym terenie mieszkańca Uśnika Kolonii, pana Józefa Korzenieckiego. Od stuleci intrygowało i fascynowało okoliczną ludność. W XIX w. próbę zbadania kurhanów podjął nauczyciel ze Śniadowa. Jednak dopiero w ubiegłym roku wojewódzki konserwator zabytków zlecił profesjonalne badania archeologiczne. Prowadzone są pod kierownictwem Mieczysława Bieni, specjalisty od wpływów rzymskich na ziemiach polskich. W ubiegłym roku zbadaliśmy kurhan oznaczony przez nas numerem 3 - poinformował M. Bienia. - Był bardzo zniszczony, zachowały się jedynie dwie warstwy kamiennego płaszcza, bezpośrednio osłaniające jamy pochówkowe. Pozwoliło nam to potwierdzić datowanie i przynależność stanowiska do tzw. kultury wielbarskiej, wiązanej ze skandynawskim plemieniem Gotów. Uzyskaliśmy bogaty materiał, poszerzający wiedzę o tej kulturze.",
      "Najcenniejszym znaleziskiem były fragmenty ceramiki z niespotykanym jeszcze nigdzie ornamentem. Według Mieczysława Bieni, jeśli podobna ceramika zostanie znaleziona w obecnie badanym kurhanie, będzie to podstawą do wprowadzenie w archeologii terminu -ceramika z Uśnika-. Od tygodnia archeolodzy badają kurhan oznaczony numerem 6. Odsłonięta została kamienna konstrukcja grobowca, która w przeciwieństwie do poprzedniego, okazała się prawie całkowicie nienaruszona. Przystąpiono do zdejmowania kolejnych warstw kamieni. Będzie ich prawdopodobnie od sześciu do ośmiu. Oczekiwane jest odsłonięcie dwóch tzw. jam pochówkowych. Gotowie grzebali swych zmarłych bądź po kremacji zwłok, bądź bez kremacji. Z dotychczasowych ustaleń wynika, że w Uśniku znajduje się cmentarzysko ciałopalne. Jeden kurhan kryje z reguły dwa pochówki. Według specjalistów w ten sposób grzebano wyłącznie kobiety. Świadczą o tym znaleziska, stanowiące tzw. wyposażenie zmarłych. Są to ozdoby kobiece i naczynia codziennego użytku. Nie ma w tych grobach przedmiotów z żelaza, w tym broni.",
      "Plemię to prawdopodobnie praktykowało odmienny rodzaj pochówków dla kobiet i odmienny dla mężczyzn. Przypuszcza się, że ciała mężczyzn, w postaci popiołu lub całych zwłok, umieszczano na kłodach drewnianych bądź innych przedmiotach pływających i puszczano z biegiem rzek, by spłynęły do morza, a stamtąd do praojczyzny Gotów - krainy zwanej Gotlandia, położonej w dzisiejszej Szwecji - wyjaśnia Mieczysław Bienia. Pracą archeologów bardzo interesują się okoliczni mieszkańcy. Badacze są otwarci na wizyty uczniów z pobliskich szkół oraz osób dorosłych. Obszernie opowiadają o swojej pracy, dzielą się wiedzą, którą czerpią z ziemi. Uważają, że jest to ich powinność - pracują po to, by mieszkańcy poznali przeszłość miejsca, w którym żyją, uświadomili sobie swoje korzenie. Mieszkańcy z kolei rewanżują się informacjami, które wzbogacają wiedzę archeologów. Dzięki m.in. relacji jednej z kobiet, pochodzącej z Rydzewa w gm. Miastkowo, powstał trop, który być może doprowadzi do odkrycia grobowca ksążęcego z okresu kultury wielbarskiej.",
    ],
  },
  {
    id: 7,
    title: "Królewskie półgrosze i prehistoryczny krzemień",
    subHeader:
      "Archeolog Mieczysław Bienia, który bada teren Parku Radziwiłłowskiego w ostatnim czasie notuje nieprzerwane pasmo sukcesów.",
    coordinates: [23.114914554938686, 52.03131588910012],
    content: [
      "Archeolog Mieczysław Bienia, który bada teren Parku Radziwiłłowskiego w ostatnim czasie notuje nieprzerwane pasmo sukcesów. Nie dość, że znalazł bialską porcelanę wytwarzaną w mieście za czasów Anny z Sanguszków Radziwiłłowej, której szukał przez ostatnie trzydzieści lat. Natrafił też na inne cenne znaleziska jak np. fragmenty armaty czy monetę wybitą w okresie panowania króla Zygmunta Starego.",
      "W Parku Radziwiłłowskim zebrano ok. 100 tys. znalezisk, które mieszczą się w 280 niemałych pudełkach. W jednym pudełku znajduje się od 300 do 600 zabytków.",
      "– Obecnie jesteśmy w trakcie prac, które prowadzimy głównie w kuchni pałacowej. Są to szeroko płaszczyznowe badania wykopaliskowe. Badamy też południową część obszaru położonego  za kuchniami, gdzie też jest wiele ciekawych zabytków, gdyż często niepotrzebne rzeczy były wyrzucane za okno. Stamtąd mamy piękną kolekcję fragmentów kafli, ceramiki i szkła.  Podobne znaleziska wykopaliśmy w pomieszczeniach kuchennych – mówi archeolog Mieczysław Bienia.",
      "Dodaje, że dokonał bardzo ważnego dla Białej odkrycia – odnalazł porcelanę bialską, której poszukiwał przez ostatnie trzydzieści lat.",
      "– Jest sygnowana literą „B” i wielokropkiem obok jest A lub cyrkiel wolnomularski. To klasyczna ceramika produkowana w Białej w czasach Anny z Sanguszków Radziwiłłowej. W farfurni, która mieściła się blisko urzędu miasta, tam gdzie swojego czasu był sklep „Anka”. Znajdowały się w niej trzy piece do wypału. W jednym wypalano ceramikę zwykłą, w dwóch pozostałych fajans i porcelanę - informuje. – Ceramika była przepiękna, bogato zdobiona. Wytwarzano talerze, misy, dzbany, kubki, filiżanki. Porcelanę dostarczano na dwór bialski, ale zapewne też na inne dwory być może też na dwór w Nieświeżu. Ciekawostką jest, że na wielu naczyniach namalowane są muchy, to tajemniczy motyw producenta – wyjaśnia archeolog.",
      "Żartując przyznaje, że nie wie czy to miało obrzydzić jedzenie czy był to znak fachowca, który wypalał porcelanę",
    ],
    date: "20/08/2021",
    images: [
      "/assets/prasa/izis-krolewskie-polgrosze-i-prehistoryczny-krzemien.webp",
    ],
    source: "Słowo Podlasia",
    url: "/prasa-o-nas/krolewskie-polgrosze-i-prehistoryczny-krzemien",
    type: "salvage-excavation-research",
  },
  {
    id: 8,
    title: "Miasto planuje odbudowę oranżerii",
    type: "archaeological-supervision-earthworks",
    images: ["/assets/prasa/izis-miasto-planuje-odbudowe-oranzerii.webp"],
    coordinates: [23.114914554938686, 52.03131588910012],
    date: "31/01/2024",
    source: "Słowo Podlasia",
    subHeader:
      "Pięć firm zgłosiło się do projektowania oranżerii, którą władze miasta chcą zbudować na nowo. Wytyczne do projektu są bardzo konkretne, a wybrana firma będzie miała na jego stworzenie 7 miesięcy.",
    url: "/prasa-o-nas/miasto-planuje-odbudowe-oranzerii",
    content: [
      "Pięć firm zgłosiło się do projektowania oranżerii, którą władze miasta chcą zbudować na nowo. Wytyczne do projektu są bardzo konkretne, a wybrana firma będzie miała na jego stworzenie 7 miesięcy.",
      "Z końcem stycznia opublikowano oferty, jakie wpłynęły w przetargu na wykonanie dokumentacji projektowej dla zadania pn.: „Odbudowa budynku oranżerii wraz z adaptacją piwnicy przy zachowaniu jej historycznego charakteru wraz z zagospodarowaniem terenu, uzbrojeniem w sieci wod.-kan., c.o. przyłączem energetycznym i instalacjami wewnętrznymi w Zespole Zamkowo – Parkowym Radziwiłłów w Białej Podlaskiej ”.",
      "Miasto przeznaczyło na ten cel 170 tys. zł, natomiast przedłożone oferty zamykają się między 178 tys. 350 zł a 615 tys. zł.",
      "Wymogi stawiane wykonawcom dokumentacji projektowej są bardzo konkretne. Wytyczne do nich przedłożył konserwator zabytków. W opisie zadania, jakie postawiono przed projektantami czytamy, że budynek powinien posiadać charakter pawilonu ogrodowego, z przestrzenią otwartą w postaci tarasu lub podcienia. Budynek ma zostać pobudowany na fundamentach zlokalizowanych poza obrysem zabytkowych piwnic.",
      "Piwnice w parku Radziwiłła zostały odkryte w ubiegłym roku. W kwietniu zespół Mieczysława Bieni rozpoczął prace w odkrytych ruinach części pałacowych, w dokumentach zapisanych jako archiwum biblioteki, a przez badaczy uważanych za strefę relaksu właścicieli pałacu. Budynek powstał w połowie XVIII wieku, najprawdopodobniej za czasów Hieronima Floriana Radziwiłła. Został odkryty w związku z zaplanowaną w tym miejscu inwestycją związaną z odbudową pawilonu oranżerii. ",
      "– Dziś możemy zobaczyć jak wyglądają te mury. Liczymy na to, że te mury podkonserwowane będą widoczne wewnątrz pobudowanego tu budynku – mówił wiosną ubiegłego roku Mieczysław Bienia, szef działu archeologii w MPP w Białej Podlaskiej. ",
      "Zgodnie z wytycznymi dla projektantów, którzy będą tworzyć dokumentację oranżerii: „(…) należy opracować szczegółowy projekt aranżacji zabytkowych piwnic ze wskazaniem fragmentów do przemurowania, uzupełnienia rekonstrukcji. Należy utrzymać zachowaną, odsłoniętą w trakcie badań archeologicznych zabytkową strukturę murów. Spoiny do uzupełnień i przemurowań powinny być analogiczne (…) do zachowanych spoin historycznych, posadzka ceglana”.",
      "Zaprojektowany budynek ma być dostosowany do całorocznego użytkowania. Ma posiadać zaplecze socjalno-sanitarne dla pracowników pawilonu, toalety, pomieszczenia ekspozycyjne z wyposażeniem wystawienniczym i multimediami, pracownię ochrony zbiorów wraz z wyposażeniem, szatnię.",
      "Miasto określiło termin wykonania dokumentacji projektowej na 7 miesięcy od podpisania umowy z wyłonionym wykonawcą.",
      "Mieszkańcom udostępniono do oglądania eksponaty z wiosennych wykopalisk w ramach wystawy czasowej Bialskie Łazienki. - Pokazujemy kafle, ceramikę i fragment tynku z motywami róży. To były podobno girlandy zdobiące ściany, po raz pierwszy można zobaczyć jak to wyglądało, bo mamy taki fragment jednej róży zrobiony z kamyków i zdobiony muszelkami – mówił Bienia, gdy wystawę otwierano przy okazji Nocy Muzeów. ",
      "Odkopany pawilon służył rodzinie Radziwiłłów do relaksu, był wewnątrz bogato zdobiony, nie brakowało tu rzeźb i zdobień na ścianach. Udało się znaleźć fragmenty płytek pochodzących z Delft, z Niderlandów. – Są one bogato zdobione w sceny rodzajowe, ale też pokazujące rośliny, przedstawiają również Indian – opowiadał Mieczysław Bienia. Archeolodzy w trakcie prac odnaleźli części zdobiących wnętrza rzeźb wyobrażających ludzkie postacie.",
      "Jak zaznacza szef działu archeologii w MPP w Białej Podlaskiej, zespół radziwiłłowski, to chyba jeden z najlepiej przebadanych zespołów pałacowych w Polsce. Archeolodzy przebadali m.in. kuchnie pałacowe, dwie fontanny czy tzw. jamę śmietnikową.",
    ],
  },
  {
    id: 9,
    title: "Rusza cykl spotkań poświęconych historii i kulturze",
    source: "Słowo Podlasia",
    subHeader:
      "Gminny Ośrodek Kultury w Janowie Podlaskim organizuje cykl wykładów poświęconych historii i kulturze.",
    coordinates: [23.21381200618758, 52.19485559647799],
    date: "19/02/2025",
    url: "/prasa-o-nas/rusza-cykl-spotkan-poswieconych-historii-i-kulturze",
    images: [
      "/assets/prasa/izis-rusza-cykl-spotkan-poswieconych-historii-i-kulturze.webp",
    ],
    content: [
      "Gminny Ośrodek Kultury w Janowie Podlaskim organizuje cykl wykładów poświęconych historii i kulturze. Najbliższe spotkanie będzie miało miejsce 20 marca. Na wydarzenie został zaproszony Mieczysław Bienia – archeolog, który opowie o swoje pracy i odkryciach.",
      "Najbliższe spotkanie w GOK odbędzie się 20 marca, o godzinie 18.00, gościem będzie Mieczysław Bienia – archeolog, który opowie o swojej pracy i odkryciach",
      "„Spotkania z historią” to cykl wykładów i prelekcji poświęcony historii i kulturze. W związku z dużym zainteresowaniem mieszkańców gminy Janów Podlaski tą tematyką, GOK zaprasza na kolejne spotkania z ciekawymi prelegentami.",
      "– Zarezerwujcie sobie państwo czas na odwiedzenie naszej instytucji – zaznacza dyrektor GOK Renata Kaczmarek.",
      "Najbliższe spotkanie w GOK odbędzie się 20 marca, o godzinie 18.00. gościem będzie archeolog Mieczysław Bienia. Z kolei 3 kwietnia, o godzinie 18.00 w GOK będzie miało miejsce spotkanie z Piotrem Strzałkowskim – pisarzem. ",
      "Natomiast 24 kwietnia, o godz. 18.00 odbędzie się spotkanie z Krzysztofem Norblinem – świadkiem historii, podróżnikiem i pisarzem.",
    ],
    type: "salvage-excavation-research",
  },
  {
    id: 10,
    title: "Rabusie artefaktów!",
    subHeader:
      "W regionie grasują rabusie skarbów. Okradają stanowiska archeologiczne i inne miejsca, w których można znaleźć zabytkowe przedmioty.",
    coordinates: [23.233363826910498, 51.97864972241554],
    date: "18/02/2025",
    source: "Słowo Podlasia",
    images: ["/assets/prasa/izis-rabusie-artefaktow.webp"],
    content: [
      "W regionie grasują rabusie skarbów. Okradają stanowiska archeologiczne i inne miejsca, w których można znaleźć zabytkowe przedmioty. To powoduje, że historyczne miejsca tracą swój kontekst naukowy i trudno określić ich datowanie. Skarbów można poszukiwać też legalnie, ale trzeba mieć zgodę właściciela pola i konserwatora zabytków. Zabytków nie można zostawić dla siebie, chyba, że nie przyjmie ich muzeum.",
      "- W regionie zdarzają się rabunki stanowisk archeologicznych. Są grupy poszukiwawczy skarbów. Część z nich działa legalnie, czyli stara się robić to, co na co mają pozwolenie od konserwatora zabytków. Osoby prowadzące poszukiwania zgodnie z prawem, nie chodzą po stanowiskach archeologicznych. Do poszukiwań na stanowiskach archeologicznych trzeba mieć pozwolenia - mówi archeolog Mieczysław Bienia. Wskazuje, że znalezisko wyciągnięte bez obecności archeologa czy odpowiedniej wiedzy jest wyjęte z kontekstu historycznego.",
      "Przedmiot traci kontekst naukowy:",
      "- Jeżeli np. grot zostanie wyciągnięty, a później przyjdzie archeolog, żeby zbadać dane cmentarzysko okaże się, że brakuje mu datownika. Podobnie jak macewy są własnością zmarłego, tak też trzeba traktować zabytki metalowe, są one własnością danego grobu, czy kompleksu osadniczego. Co z tego, że ktoś przyniesie mi zabytki, oczywiście je przyjmę i się ucieszę, ale tracę cały kontekst naukowy. Wówczas dany przedmiot ma znikomą wartość naukową - zaznacza Mieczysław Bienia. ",
      "Dodaje, że posługuje się metodyką badań archeologicznych. - Ściągamy najpierw główną warstwę, ona jest przemieszana przez orkę zazwyczaj, jednak są miejsca, gdzie nie było orki, jak lasy, łąki. Zniszczenia są w tym miejscach mniejsze, chociaż oczywiście zdarza się, że korzenie drzew przesuwają przedmioty znajdujące się w ziemi. Jednak, dany przedmiot znajduje się w pobliżu np. cmentarzyska - przekazuje archeolog. ",
      "Zabytki sprzedają zamiast oddać muzeum:",
      "Nie ukrywa, że jeżeli archeolog trafia na cmentarzysko i tam wydobywa przedmioty, to kontekst naukowy jest bardzo ważny. - Wtedy możemy datować dane znalezisko. Jeżeli te przedmioty z tej jamy się wyrwie, to miejsce i przedmioty tracą swoja wartość. Dlatego tak ważne jest to, by nie wchodzić na stanowiska archeologiczne. Można poszukiwać rzeczy zagubionych z pasji, ale nie na stanowiskach archeologicznych. Wiele osób to szanuje, ale są całe grupy, które niestety tych zasad nie uznają. Chodząc z wykrywaczami, znajdują głównie metalowe przedmioty. Jak odsłonią taki grób, to wyciągają też naczynia, szklane paciorki, wszystko co tam się znajduje. Następnie jest to sprzedawane - mówi Mieczysław Bienia. ",
      "Zauważa, że takie przedmioty trafiają często do prywatnych kolekcji, do których nie ma dostępu. - Wiadomo, że zgodnie z ustawą wydobyte przedmioty stanowią własność Skarbu Państwa. Państwo będzie się o te przedmioty upominało. W Białej Podlaskiej działa koło Fibula, które wykonuje prace archeologiczne pod moim kierunkiem, w sposób metodyczny, nie niszcząc obiektów. W zeszłym roku prowadziliśmy takie badania w Kodniu. Kilka przedmiotów udało się znaleźć. Naturalnie, nie wszędzie udaje się dotrzeć, bo np. miejsce jest zarośnięte - przekazuje Mieczysław Bienia.",
      "Koło Fibula dokładnie rejestruje znaleziska. Powstała mapa znalezisk. - To istotny element poszukiwania. Natomiast rabusie nie przejmują się brakiem metodyki, stanowią duże zagrożenie dla poznania najstarszej historii naszego terenu. Od osób trzecich dowiaduję się, że znaleziono skarb pełen monet lub naczynia gliniane czy też ozdoby brązowe lub srebrne. Co mi po tych informacjach, skoro te przedmioty nie trafiają do mnie - mówi archeolog.",
      "Przyznaje, że kilka znalezisk zostało przekazanych do zbiorów państwowych, np. skarb monet z połowy XVII wieku, spod Jabłonia. - Z tamtego roku mamy ciekawy depozyt znaleziony poza naszym terenem, żetonów z Białej Podlaskiej z okresu międzywojennego. W tym roku będzie konserwowany, więc na pewno skarb pokażemy na wystawie, żeby mieszkańcy i turyści, którzy odwiedzają Białą Podlaską mogli się z nim zapoznać - zapowiada Mieczysław Bienia.",
      "Przyznaje też, że każdy obywatel ma prawo szukać skarbów, ale pod konkretnymi warunkami. - Po pierwsze jest potrzebna zgoda właściciela pola, my archeolodzy też nie wchodzimy na dane pole bez zgody właściciela. Z tą zgodą trzeba udać się do konserwatora zabytków i uzyskać pozwolenie na poszukiwania. Najważniejszy warunek to taki, że miejsce nie może być stanowiskiem archeologicznym. Gdy tak jest, konserwator nie wyrazi zgody na poszukiwania. Chyba, że w grupie jest archeolog i prowadzony jest program badawczy. Jest kilka takich grup zewnętrznych, które pojawiają się na naszym terenie. Zabytki od nich zazwyczaj trafiają do bialskich zbiorów muzealnych - wyjaśnia Mieczysław Bienia.",
      "Znalezione przedmioty znalazca ma obowiązek przekazać do muzeum. - Pod warunkiem, że muzeum będzie chciało mieć coś takiego w swoich zbiorach. Często są to znaleziska z XX wieku, więc muzeum nie jest tym zainteresowane. Jest znajdowanych wiele monet, które nie interesują muzeum, więc trafiają z powrotem do znalazcy. Konserwator zabytków decyduje o tym, gdzie ma trafić dane znalezisko. Szukanie na handel jest niedopuszczalne i nieetyczne - wskazuje archeolog. ",
      "Koło Fibula czeka na remont budynku muzealnego przy ul. Łomaskiej, gdyż tam miałyby się odbywać spotkania koła. - Obecnie działamy na pół gwizdka, bo nie mamy swojej siedziby. Zostało ze mną kilkanaście osób, które współpracują przy poszukiwaniach w regionie. Jednak, Fibula z czasem będzie reaktywowana, ale wstrzymaliśmy na ten moment zapisy - wyjaśnia Mieczysław Bienia. ",
      "Wójt gminy Wisznice Piotr Dragan, przyznaje, że słyszał o rabusiach skarbów działających na terenie południowego Podlasia. ",
      "- Wiem, że chodzą z wykrywaczami metalu, np. w Horodyszczu. Dowiadywałem się, że te osoby odnajdują różne przedmioty, więc bardzo krytycznie do tego podchodzę. Była pogłoska o znalezionym skarbie, więc zacząłem o to pytać, ale to zamknięte środowisko, które nie wypuszcza poza swój krąg zbyt wielu informacji. Takie działania są niekorzystne, bo to zazwyczaj o wiele cenniejsze rzeczy niż się za nie płaci na czarnym rynku. Takie artefakty mogłyby udowodnić, że na terenie gminy istniało osadnictwo przed XI wiekiem - wskazuje wójt Piotr Dragan.",
      "Dodaje, że istnieją dowody na to, że w Horodyszczu było osadnictwo w X wieku, a znalezione nielegalnie przedmioty pochodziły sprzed tego okresu. - Gdyby stary przedmiot, znaleziony przez kogoś trafił do urzędu gminy, i byłby np. z I wieku po Chrystusie lub z wcześniejszego okresu, moglibyśmy na tej bazie zacząć budować muzeum. Zewnętrznych funduszy na tego typu cele jest dużo. Problemem jest to, że osoby, które znajdują zabytki sprzedają je gdzieś za małe pieniądze, a można zamiast tego coś wielkiego dla gminy uzyskać. Niestety tylko doszły mnie słuchy, że podobna rzecz została znaleziona, ale później ślad po niej zaginął - mówi wójt gminy Wisznice Piotr Dragan.",
    ],
    url: "/prasa-o-nas/rabusie-artefaktow",
  },
] satisfies NewsCardProps[];
